name: Build and Deploy Dating App (API & Client)

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

# Track changes in specific paths (optional, adjust as needed)
paths:
  include:
    - api/*
    - client/*

# Workflow Stages (optional)
stages:
  - stage: BuildAPI
  - stage: BuildClient
  - stage: DeployAPI
    condition: eq(variables['API_DEPLOYMENT'], 'true')  # Run only for API deployments
  - stage: DeployClient
    condition: eq(variables['CLIENT_DEPLOYMENT'], 'true')  # Run only for client deployments

jobs:
  - job: Build

    steps:
      - script: dotnet build dating-app.sln -c Release  # Specify the solution file and configuration
        workingDirectory: backend  # Change directory to where the solution file resides
        displayName: 'Build .NET API'  # Update display name (optional)

  - job: Build

    steps:
      - script: npm install --legacy-peer-deps && npm run build --prod
        workingDirectory: client
        displayName: 'Build Angular Client'  # Update display name (optional)

  - deployment: Deploy (API)  # Use descriptive deployment names

    environment: 'production'  # Replace with your desired environment name (e.g., development, staging, production)
    strategy:
      runOnce:
        deploy:
          steps:
            - name: Download artifact from BuildAPI job (if building separately)
              uses: actions/download-artifact@v3
              with:
                name: .net-app  # Adjust if your artifact name is different

            - name: Deploy to Azure Web App (API)
              id: deploy-to-webapp-api
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'da-api-mr'  # Replace with your API app service name
                slot-name: 'Production'  # Replace if deploying to a different slot
                package: .  # Package location relative to the deployment step
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2706DEB79BA64D12BFFB60412AC994FA }}

  - deployment: Deploy (Client)  # Use descriptive deployment names

    environment: 'production'  # Replace with your desired environment name (e.g., development, staging, production)
    strategy:
      runOnce:
        deploy:
          steps:
            - name: Download artifact from BuildClient job (if building separately)
              uses: actions/download-artifact@v3
              with:
                name: client-artifact  # Adjust if your artifact name is different

            - name: Deploy to Azure Web App (Client)
              id: deploy-to-webapp-client
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'da-client-mr'  # Replace with your client app service name
                slot-name: 'Production'  # Replace if deploying to a different slot
                package: ./client/dist  # Adjust path if needed
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2706DEB79BA64D12BFFB60412AC994FA }}
